18 Mar 2020 12:15:19,593 ERROR StartLogger - Exception while starting logics instance: 
java.lang.RuntimeException: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at lsfusion.server.physics.exec.db.controller.manager.DBManager.initReflectionEvents(DBManager.java:199)
	at lsfusion.server.physics.admin.reflection.controller.init.InitReflectionEventsTask.run(InitReflectionEventsTask.java:13)
	at lsfusion.server.base.task.Task.proceed(Task.java:143)
	at lsfusion.server.base.task.Task$1.aspectRun(Task.java:101)
	at lsfusion.server.base.controller.thread.ExecutorFactory$AspectRunnable.run(ExecutorFactory.java:465)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
	at lsfusion.server.base.controller.thread.ExecutorFactory$ClosableDaemonThreadFactory$ClosableThread.run(ExecutorFactory.java:536)
Caused by: org.postgresql.util.PSQLException: FATAL: password authentication failed for user "postgres"
	at org.postgresql.core.v3.ConnectionFactoryImpl.doAuthentication(ConnectionFactoryImpl.java:520)
	at org.postgresql.core.v3.ConnectionFactoryImpl.tryConnect(ConnectionFactoryImpl.java:141)
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:192)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:195)
	at org.postgresql.Driver.makeConnection(Driver.java:458)
	at org.postgresql.Driver.connect(Driver.java:260)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:677)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:251)
	at lsfusion.server.data.sql.adapter.PostgreDataAdapter.ensureDB(PostgreDataAdapter.java:74)
	at lsfusion.server.data.sql.adapter.DataAdapter.ensure(DataAdapter.java:68)
	at lsfusion.server.physics.exec.db.controller.manager.DBManager.initReflectionEvents(DBManager.java:187)
	... 8 more
19 мар 2020 15:03:08,227 ERROR LogicsModule - lsfusion.gwt.client.base.exception.RemoteRetryException no such object in table at '19.03.20 15:03' from '0:0:0:0:0:0:0:1 - web': 
null
	at java.lang.Throwable.Throwable(Throwable.java:60)
	at java.lang.Exception.Exception(Exception.java:25)
	at net.customware.gwt.dispatch.shared.DispatchException.DispatchException(DispatchException.java:15)
	at lsfusion.gwt.client.base.exception.RemoteRetryException.RemoteRetryException(RemoteRetryException.java:8)
	at lsfusion.gwt.client.base.exception.RemoteRetryException_FieldSerializer.instantiate(RemoteRetryException_FieldSerializer.java:17)
	at com.google.gwt.user.client.rpc.impl.SerializerBase$MethodMap.$instantiate(SerializerBase.java:55)
	at com.google.gwt.user.client.rpc.impl.SerializerBase.$instantiate(SerializerBase.java:112)
	at com.google.gwt.user.client.rpc.impl.AbstractSerializationStreamReader.$readObject(AbstractSerializationStreamReader.java:129)
	at com.google.gwt.user.client.rpc.impl.RequestCallbackAdapter.$onResponseReceived(RequestCallbackAdapter.java:216)
	at com.google.gwt.http.client.Request.$fireOnResponseReceived(Request.java:250)
	at com.google.gwt.http.client.RequestBuilder$1.onReadyStateChange(RequestBuilder.java:412)
	at Unknown.anonymous(Unknown Source)
	at com.google.gwt.core.client.impl.Impl.apply(Impl.java:309)
	at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:368)
	at Unknown.anonymous(Unknown Source)

19 мар 2020 15:10:46,896 ERROR LogicsModule - lsfusion.gwt.client.base.exception.RemoteRetryException no such object in table at '19.03.20 15:10' from '0:0:0:0:0:0:0:1 - web': 
null
	at java.lang.Throwable.Throwable(Throwable.java:60)
	at java.lang.Exception.Exception(Exception.java:25)
	at net.customware.gwt.dispatch.shared.DispatchException.DispatchException(DispatchException.java:15)
	at lsfusion.gwt.client.base.exception.RemoteRetryException.RemoteRetryException(RemoteRetryException.java:8)
	at lsfusion.gwt.client.base.exception.RemoteRetryException_FieldSerializer.instantiate(RemoteRetryException_FieldSerializer.java:17)
	at com.google.gwt.user.client.rpc.impl.SerializerBase$MethodMap.$instantiate(SerializerBase.java:55)
	at com.google.gwt.user.client.rpc.impl.SerializerBase.$instantiate(SerializerBase.java:112)
	at com.google.gwt.user.client.rpc.impl.AbstractSerializationStreamReader.$readObject(AbstractSerializationStreamReader.java:129)
	at com.google.gwt.user.client.rpc.impl.RequestCallbackAdapter.$onResponseReceived(RequestCallbackAdapter.java:216)
	at com.google.gwt.http.client.Request.$fireOnResponseReceived(Request.java:250)
	at com.google.gwt.http.client.RequestBuilder$1.onReadyStateChange(RequestBuilder.java:412)
	at Unknown.anonymous(Unknown Source)
	at com.google.gwt.core.client.impl.Impl.apply(Impl.java:309)
	at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:368)
	at Unknown.anonymous(Unknown Source)

19 мар 2020 15:12:04,721 ERROR LogicsModule - lsfusion.gwt.client.base.exception.RemoteRetryException no such object in table at '19.03.20 15:12' from '0:0:0:0:0:0:0:1 - web': 
null
	at java.lang.Throwable.Throwable(Throwable.java:60)
	at java.lang.Exception.Exception(Exception.java:25)
	at net.customware.gwt.dispatch.shared.DispatchException.DispatchException(DispatchException.java:15)
	at lsfusion.gwt.client.base.exception.RemoteRetryException.RemoteRetryException(RemoteRetryException.java:8)
	at lsfusion.gwt.client.base.exception.RemoteRetryException_FieldSerializer.instantiate(RemoteRetryException_FieldSerializer.java:17)
	at com.google.gwt.user.client.rpc.impl.SerializerBase$MethodMap.$instantiate(SerializerBase.java:55)
	at com.google.gwt.user.client.rpc.impl.SerializerBase.$instantiate(SerializerBase.java:112)
	at com.google.gwt.user.client.rpc.impl.AbstractSerializationStreamReader.$readObject(AbstractSerializationStreamReader.java:129)
	at com.google.gwt.user.client.rpc.impl.RequestCallbackAdapter.$onResponseReceived(RequestCallbackAdapter.java:216)
	at com.google.gwt.http.client.Request.$fireOnResponseReceived(Request.java:250)
	at com.google.gwt.http.client.RequestBuilder$1.onReadyStateChange(RequestBuilder.java:412)
	at Unknown.anonymous(Unknown Source)
	at com.google.gwt.core.client.impl.Impl.apply(Impl.java:309)
	at com.google.gwt.core.client.impl.Impl.entry0(Impl.java:368)
	at Unknown.anonymous(Unknown Source)

